spring.application.name=demo

spring.datasource.url=jdbc:mysql://jointless-mysql-jointless.f.aivencloud.com:24582/ defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_1WofJ1gRMWf3WkJtHdm

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

