spring.application.name=demo

spring.datasource.url=jdbc:mysql://jointless-mysql-jointless.f.aivencloud.com:24582/defaultdb?ssl-mode=REQUIRED&useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_1WofJ1gRMWf3WkJtHdm

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret-key=4faa3e462cd5f4eb227292134d78efe08b2979bee938ad8f6c03f4d9b4c7ba06
jwt.expiration=3600000