spring.application.name=demo

spring.datasource.url=jdbc:mysql://jointless-mysql-jointless.f.aivencloud.com:24582/defaultdb?ssl-mode=REQUIRED&useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_1WofJ1gRMWf3WkJtHdm

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=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
groq.api.model=llama-3.3-70b-versatile